/*globals define*/
/*eslint-env node, browser*/

/**
 * Generated by PluginGenerator 2.20.5 from webgme on Tue Jun 27 2023 22:56:29 GMT-0500 (Central Daylight Time).
 * A plugin that inherits from the PluginBase. To see source code documentation about available
 * properties and methods visit %host%/docs/source/PluginBase.html.
 */

define([
    'plugin/PluginConfig',
    'text!./metadata.json',
    'plugin/PluginBase',
    'webgme-cwl/config'
], function (
    PluginConfig,
    pluginMetadata,
    PluginBase,
    CONFIG) {
    'use strict';

    pluginMetadata = JSON.parse(pluginMetadata);

    /**
     * Initializes a new instance of OpenDashboard.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin OpenDashboard.
     * @constructor
     */
    function OpenDashboard() {
        // Call base class' constructor.
        PluginBase.call(this);
        this.pluginMetadata = pluginMetadata;
    }

    /**
     * Metadata associated with the plugin. Contains id, name, version, description, icon, configStructure etc.
     * This is also available at the instance at this.pluginMetadata.
     * @type {object}
     */
    OpenDashboard.metadata = pluginMetadata;

    // Prototypical inheritance from PluginBase.
    OpenDashboard.prototype = Object.create(PluginBase.prototype);
    OpenDashboard.prototype.constructor = OpenDashboard;

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(Error|null, plugin.PluginResult)} callback - the result callback
     */
    OpenDashboard.prototype.main = function (callback) {
        window.open(CONFIG.getDashboardUrl(), "Dashboard");
        this.result.setSuccess(true);
        callback(null, this.result);
    };

    return OpenDashboard;
});
