// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push(__dirname + '/../src/plugins');
config.plugin.basePaths.push(__dirname + '/../node_modules/webgme-json/src/plugins');
config.seedProjects.basePaths.push(__dirname + '/../src/seeds/CWL');



config.visualization.panelPaths.push(__dirname + '/../node_modules/webgme-json/src/visualizers/panels');
config.visualization.panelPaths.push(__dirname + '/../src/visualizers/panels');




// Visualizer descriptors
config.visualization.visualizerDescriptors.push(__dirname + '/../src/visualizers/Visualizers.json');
// Add requirejs paths
config.requirejsPaths = {
  'CreateConfig': 'node_modules/webgme-json/src/plugins/CreateConfig',
  'JSONToModel': 'node_modules/webgme-json/src/plugins/JSONToModel',
  'ModelToJSON': 'node_modules/webgme-json/src/plugins/ModelToJSON',
  'ImportJSON': 'node_modules/webgme-json/src/plugins/ImportJSON',
  'ExportJSON': 'node_modules/webgme-json/src/plugins/ExportJSON',
  'TextualJSONEditor': 'panels/TextualJSONEditor/TextualJSONEditorPanel',
  'panels': './src/visualizers/panels',
  'widgets': './src/visualizers/widgets',
  'panels/TextualJSONEditor': './node_modules/webgme-json/src/visualizers/panels/TextualJSONEditor',
  'widgets/TextualJSONEditor': './node_modules/webgme-json/src/visualizers/widgets/TextualJSONEditor',
  'webgme-json': './node_modules/webgme-json/src/common',
  'webgme-cwl': './src/common'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/webgme_cwl';
validateConfig(config);
module.exports = config;
