/*globals define, _, WebGMEGlobal*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue Mar 08 2022 12:59:55 GMT-0600 (Central Standard Time).
 */

define([
    'js/PanelBase/PanelBaseWithHeader',
    'js/PanelManager/IActivePanel',
    'webgme-cwl/bundles/CommonWorkflowEditorWidget.bundle',
    './CommonWorkflowEditorControl',
    'css!webgme-cwl/bundles/styles/CommonWorkflowEditorWidget.bundle.css'
], function (
    PanelBaseWithHeader,
    IActivePanel,
    CommonWorkflowEditorWidget,
    CommonWorkflowEditorControl
) {
    'use strict';

    function CommonWorkflowEditorPanel(layoutManager, params) {
        var options = {};
        //set properties from options
        options[PanelBaseWithHeader.OPTIONS.LOGGER_INSTANCE_NAME] = 'CommonWorkflowEditorPanel';
        options[PanelBaseWithHeader.OPTIONS.FLOATING_TITLE] = true;

        //call parent's constructor
        PanelBaseWithHeader.apply(this, [options, layoutManager]);

        this._client = params.client;
        this.appId = `my-react-viz-id`;

        //initialize UI
        this._initialize();

        this.logger.debug('ctor finished');
    }

    //inherit from PanelBaseWithHeader
    _.extend(CommonWorkflowEditorPanel.prototype, PanelBaseWithHeader.prototype);
    _.extend(CommonWorkflowEditorPanel.prototype, IActivePanel.prototype);

    CommonWorkflowEditorPanel.prototype._initialize = function () {
        var self = this;

        this.$el.prop('id', this.appId);
        this.$el.css({
            width: '100%',
            height: '100%',
        });

        //set Widget title
        // this.setTitle('');

        // this.widget = new CommonWorkflowEditorWidget(this.logger, this.$el);

        // this.widget.setTitle = function (title) {
            // self.setTitle(title);
        // };

        this.control = new CommonWorkflowEditorControl({
            logger: this.logger,
            client: this._client,
            widget: this.widget
        });

        this.onActivate();
    };

    CommonWorkflowEditorPanel.prototype.afterAppend = function afterAppend() {
        console.log('AFTER APPEND');
        CommonWorkflowEditorWidget(this.appId, this.control, this);
    };

    /* OVERRIDE FROM WIDGET-WITH-HEADER */
    /* METHOD CALLED WHEN THE WIDGET'S READ-ONLY PROPERTY CHANGES */
    CommonWorkflowEditorPanel.prototype.onReadOnlyChanged = function (isReadOnly) {
        //apply parent's onReadOnlyChanged
        PanelBaseWithHeader.prototype.onReadOnlyChanged.call(this, isReadOnly);

    };

    CommonWorkflowEditorPanel.prototype.onResize = function (width, height) {
        this.logger.debug('onResize --> width: ' + width + ', height: ' + height);
        // this.widget.onWidgetContainerResize(width, height);
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    CommonWorkflowEditorPanel.prototype.destroy = function () {
        this.control.destroy();
        // this.widget.destroy();

        PanelBaseWithHeader.prototype.destroy.call(this);
        WebGMEGlobal.KeyboardManager.setListener(undefined);
        WebGMEGlobal.Toolbar.refresh();
    };

    CommonWorkflowEditorPanel.prototype.onActivate = function () {
        // this.widget.onActivate();
        this.control.onActivate();
        WebGMEGlobal.KeyboardManager.setListener(this.widget);
        WebGMEGlobal.Toolbar.refresh();
    };

    CommonWorkflowEditorPanel.prototype.onDeactivate = function () {
        // this.widget.onDeactivate();
        this.control.onDeactivate();
        WebGMEGlobal.KeyboardManager.setListener(undefined);
        WebGMEGlobal.Toolbar.refresh();
    };

    return CommonWorkflowEditorPanel;
});
